// <auto-generated />
using HotelListing.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.API.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    [Migration("20250413120254_seededCountriesAndHotels")]
    partial class seededCountriesAndHotels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelListing.API.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "United States",
                            ShortName = "US"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United Kingdom",
                            ShortName = "UK"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Canada",
                            ShortName = "CA"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Australia",
                            ShortName = "AU"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Germany",
                            ShortName = "DE"
                        },
                        new
                        {
                            Id = 6,
                            Name = "France",
                            ShortName = "FR"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Italy",
                            ShortName = "IT"
                        });
                });

            modelBuilder.Entity("HotelListing.API.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Los Angeles, CA",
                            CountryId = 1,
                            Name = "Hotel California",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "150 Piccadilly, London W1J 9BR, UK",
                            CountryId = 2,
                            Name = "The Ritz London",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "405 Spray Ave, Banff, AB T1L 1J4, Canada",
                            CountryId = 3,
                            Name = "Fairmont Banff Springs",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 4,
                            Address = "Bennelong Point, Sydney NSW 2000, Australia",
                            CountryId = 4,
                            Name = "Sydney Opera House Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 5,
                            Address = "Unter den Linden 77, 10117 Berlin, Germany",
                            CountryId = 5,
                            Name = "Hotel Adlon Kempinski",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 6,
                            Address = "228 Rue de Rivoli, 75001 Paris, France",
                            CountryId = 6,
                            Name = "Le Meurice",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 7,
                            Address = "Riva degli Schiavoni, 4196, 30122 Venezia VE, Italy",
                            CountryId = 7,
                            Name = "Hotel Danieli",
                            Rating = 4.7999999999999998
                        });
                });

            modelBuilder.Entity("HotelListing.API.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.API.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.API.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
